---
- name: Remove old docker packages
  become: yes
  run_once: true
  apt:
    force_apt_get: yes # should be fixed in future to remove "[WARNING]: Could not find aptitude. Using apt-get instead" 
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent

- name: Install docker prerequisites
  become: yes
  run_once: true
  apt:
    force_apt_get: yes # should be fixed in future to remove "[WARNING]: Could not find aptitude. Using apt-get instead" 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent' ,'software-properties-common']
    update_cache: yes

- name: Add Docker GPG key
  become: yes
  run_once: true
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  become: yes
  run_once: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  become: yes
  run_once: true
  apt:
    force_apt_get: yes # should be fixed in future to remove "[WARNING]: Could not find aptitude. Using apt-get instead" 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes

- name: Retrieve last docker-compose version
  run_once: true
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: curl_dockercompose

# Example setting host facts using complex arguments
- set_fact:
     docker_compose_version: "{{ curl_dockercompose.json.name }}"

- name: Install Docker-compose {{ docker_compose_version }}
  run_once: true
  become: yes
  #  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #TODO we should retrieve last version of docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: +x

